In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\spam.csv")
df.head(4)

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...


In [21]:
df["Spam"] = df["Category"].apply(lambda x : 1 if x =="spam" else 0 )

In [22]:
df.head()

,Category,Message,Spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [23]:
X_train, X_test, y_train, y_test = train_test_split(df["Message"], df["Spam"], test_size=0.33, random_state=42)

In [24]:
len(X_train)

3733

In [25]:
len(X_test)

1839

In [26]:
X_train.shape

(3733,)

In [27]:
cv = CountVectorizer()

In [28]:
X_train_cv = cv.fit_transform(X_train.values)
X_text_cv = cv.transform(X_test.values)

In [29]:
X_train_cv.shape

(3733, 7081)

In [30]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 49971 stored elements and shape (3733, 7081)>

In [31]:
cv.get_feature_names_out()[5008]

'protect'

In [32]:
cv.vocabulary_

{'yup': 7068,
 'not': 4414,
 'comin': 1735,
 'sent': 5511,
 'my': 4269,
 'scores': 5442,
 'to': 6329,
 'sophas': 5790,
 'and': 877,
 'had': 3007,
 'do': 2155,
 'secondary': 5467,
 'application': 934,
 'for': 2676,
 'few': 2565,
 'schools': 5436,
 'think': 6246,
 'if': 3279,
 'you': 7047,
 'are': 956,
 'thinking': 6249,
 'of': 4469,
 'applying': 937,
 'research': 5242,
 'on': 4512,
 'cost': 1834,
 'also': 848,
 'contact': 1796,
 'joke': 3500,
 'ogunrinde': 4488,
 'her': 3115,
 'school': 5435,
 'is': 3415,
 'one': 4517,
 'me': 4017,
 'the': 6218,
 'less': 3725,
 'expensive': 2471,
 'ones': 4518,
 'kothi': 3620,
 'print': 4958,
 'out': 4582,
 'marandratha': 3965,
 'its': 3435,
 'just': 3531,
 'effect': 2309,
 'irritation': 3413,
 'ignore': 3282,
 'it': 3427,
 'asked': 995,
 'call': 1453,
 'him': 3132,
 'now': 4425,
 'ok': 4493,
 'whatever': 6827,
 'juliana': 3523,
 'want': 6743,
 'hello': 3102,
 'got': 2925,
 'here': 3116,
 'st': 5880,
 'andrews': 880,
 'boy': 1330,
 'long': 3822,
 'way':

In [33]:
X_train_arr = X_train_cv.toarray()

In [34]:
X_train_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
mm = MultinomialNB()

In [37]:
mm.fit(X_train_cv,y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [38]:
y_pred = mm.predict(X_text_cv)

In [39]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1593
           1       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



# test model

In [44]:
msg = {"Exact IT Solutions Pvt. Ltd. and 19 more companies are hiring Software Engineer"}

In [45]:
result = cv.transform(msg)
mm.predict(result)

array([0])

In [57]:
nw = {"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"}

In [58]:
result = cv.transform(nw)
mm.predict(result)

array([1])